os: Visual Studio 2017
platform: x64

#
# Build
#
build_script:

  #
  # Visual Studio
  #
  - mkdir build_msvc
  - cd build_msvc
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --config Debug
  - ctest -C Debug
  - cd ..                                                        